# Generated by Django 3.2.15 on 2022-09-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_localstack_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
