# Generated by Django 4.1 on 2022-09-26 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_page_image_file_alter_page_followers'),
        ('users', '0002_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='blog.post'),
        ),
    ]
