# Generated by Django 4.1 on 2022-09-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_image_localstack_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_of_ban',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
