# Generated by Django 4.1 on 2022-09-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_time_of_ban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time_of_ban',
        ),
        migrations.AddField(
            model_name='user',
            name='bantime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
