# Generated by Django 4.1 on 2022-09-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_time_of_ban_user_bantime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bantime',
            field=models.IntegerField(blank=True, default=5),
            preserve_default=False,
        ),
    ]
