# Generated by Django 4.1 on 2022-09-21 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_bantime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bantime',
        ),
        migrations.AddField(
            model_name='user',
            name='time_before_unban',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
