# Generated by Django 4.1 on 2022-09-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_bantime_user_time_before_unban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_before_unban',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
